---
verison: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - pip
      - security
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - docker
      - security
