repos:
- repo: https://github.com/hadolint/hadolint
  rev: v2.0.0
  hooks:
  - id: hadolint-docker
    args:
    - --ignore
    - DL3005
    - --ignore
    - DL3008
    - "-"
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml

