repos:
- repo: local
  hooks:
    - id: hadolint
      name: hadolint
      description: Dockerfile linter
      language: docker_image
      types:
        - dockerfile
      pass_filenames: true
      entry: hadolint/hadolint:latest hadolint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml

